### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by jaens** [augustwester/searchthearxiv#1]
The `https://searchthearxiv.com/search?query=` endpoint seems to be currently returning `500 Internal Server Error`.

**Comment by augustwester** [comment]
I'm unable to reproduce this. Are you still experiencing the issue?

**Comment by jaens** [comment]
Yep, for example the request: `https://searchthearxiv.com/search?query=https%3A%2F%2Farxiv.org%2Fabs%2F2203.09452` (searching for `https://arxiv.org/abs/2203.09452`)

**Comment by augustwester** [comment]
Thanks for the clarification. I think I've found the problem. Will be pushing a fix soon.

**Comment by augustwester** [comment]
Should be working now. The problem was due to faulty handling of papers not already in the database (like the one you referred to). Thanks for letting me know! 👍
